source 'https://rubygems.org'
ruby '2.5.1'

gem 'json'
gem 'appium_lib',         '~> 10.3.1'
gem 'rest-client',        '~> 2.0.2'
gem 'rspec',              '~> 3.6.0'
gem 'rspec-expectations', '~> 3.6.0'
gem 'spec',               '~> 5.3.4'
gem 'sauce_whisk',        '~> 0.0.13'
gem 'test-unit',          '~> 2.5.5'
gem 'faker',              '~> 1.6'
gem 'american_date',      '~> 1.1'
gem 'appom',              '~> 1.1'
gem 'cucumber',           '~> 3.1'
gem 'rake',               '~> 13.0'
gem 'dotenv'


gem 'nokogiri',           '>= 1.10.7'
gem 'rubyzip',            '>= 1.3.0'